remove unneeded spaces & convert indentation to spaces

diff --git a/init.d/Nginx-init-Ubuntu b/init.d/Nginx-init-Ubuntu
--- a/init.d/Nginx-init-Ubuntu
+++ b/init.d/Nginx-init-Ubuntu
@@ -9,13 +9,13 @@
 # Description:       nginx init.d dash script for Ubuntu <=9.10.
 ### END INIT INFO
 #------------------------------------------------------------------------------
-# nginx - this Debian Almquist shell (dash) script, starts and stops the nginx 
+# nginx - this Debian Almquist shell (dash) script, starts and stops the nginx
 #         daemon for ubuntu 9.10 and lesser version numbered releases.
 #
 # description:  Nginx is an HTTP(S) server, HTTP(S) reverse \
 #               proxy and IMAP/POP3 proxy server.  This \
-#		script will manage the initiation of the \
-#		server and it's process state.
+#       script will manage the initiation of the \
+#       server and it's process state.
 #
 # processname: nginx
 # config:      /usr/local/nginx/conf/nginx.conf
@@ -27,77 +27,77 @@
 #
 # Version: 2.0 02-NOV-2009 jason.giedymin AT gmail.com
 # Notes: nginx init.d dash script for Ubuntu <=9.10.
-# 
+#
 # This script's project home is:
-# 	http://code.google.com/p/nginx-init-ubuntu/
+#   http://code.google.com/p/nginx-init-ubuntu/
 #
 #------------------------------------------------------------------------------
 #                               Functions
 #------------------------------------------------------------------------------
 . /lib/lsb/init-functions
- 
+
 #------------------------------------------------------------------------------
 #                               Consts
 #------------------------------------------------------------------------------
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/local/nginx/sbin/nginx
- 
+
 PS="nginx"
-PIDNAME="nginx"				#lets you do $PS-slave
+PIDNAME="nginx"             #lets you do $PS-slave
 PIDFILE=$PIDNAME.pid                    #pid file
 PIDSPATH=/var/run
- 
+
 DESCRIPTION="Nginx Server..."
- 
+
 RUNAS=root                              #user to run as
- 
+
 SCRIPT_OK=0                             #ala error codes
 SCRIPT_ERROR=1                          #ala error codes
 TRUE=1                                  #boolean
 FALSE=0                                 #boolean
- 
+
 lockfile=/var/lock/subsys/nginx
 NGINX_CONF_FILE="/usr/local/nginx/conf/nginx.conf"
- 
+
 #------------------------------------------------------------------------------
 #                               Simple Tests
 #------------------------------------------------------------------------------
- 
+
 #test if nginx is a file and executable
 test -x $DAEMON || exit 0
- 
+
 # Include nginx defaults if available
 if [ -f /etc/default/nginx ] ; then
         . /etc/default/nginx
 fi
- 
+
 #set exit condition
 #set -e
- 
+
 #------------------------------------------------------------------------------
 #                               Functions
 #------------------------------------------------------------------------------
- 
+
 setFilePerms(){
- 
+
         if [ -f $PIDSPATH/$PIDFILE ]; then
                 chmod 400 $PIDSPATH/$PIDFILE
         fi
 }
- 
+
 configtest() {
-	$DAEMON -t -c $NGINX_CONF_FILE
+    $DAEMON -t -c $NGINX_CONF_FILE
 }
- 
+
 getPSCount() {
-	return `pgrep -f $PS | wc -l`
+    return `pgrep -f $PS | wc -l`
 }
- 
+
 isRunning() {
         if [ $1 ]; then
                 pidof_daemon $1
                 PID=$?
- 
+
                 if [ $PID -gt 0 ]; then
                         return 1
                 else
@@ -106,7 +106,7 @@ isRunning() {
         else
                 pidof_daemon
                 PID=$?
- 
+
                 if [ $PID -gt 0 ]; then
                         return 1
                 else
@@ -114,13 +114,13 @@ isRunning() {
                 fi
         fi
 }
- 
+
 #courtesy of php-fpm
 wait_for_pid () {
         try=0
- 
+
         while test $try -lt 35 ; do
- 
+
                 case "$1" in
                         'created')
                         if [ -f "$2" ] ; then
@@ -128,7 +128,7 @@ wait_for_pid () {
                                 break
                         fi
                         ;;
- 
+
                         'removed')
                         if [ ! -f "$2" ] ; then
                                 try=''
@@ -136,45 +136,45 @@ wait_for_pid () {
                         fi
                         ;;
                 esac
- 
+
                 #echo -n .
                 try=`expr $try + 1`
                 sleep 1
         done
 }
- 
+
 status(){
-	isRunning
-	isAlive=$?
- 
-	if [ "${isAlive}" -eq $TRUE ]; then
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
                 echo "$PIDNAME found running with processes:  `pidof $PS`"
         else
                 echo "$PIDNAME is NOT running."
         fi
- 
- 
+
+
 }
- 
+
 removePIDFile(){
-	if [ $1 ]; then
+    if [ $1 ]; then
                 if [ -f $1 ]; then
-        	        rm -f $1
-	        fi
+                    rm -f $1
+            fi
         else
-		#Do default removal
-		if [ -f $PIDSPATH/$PIDFILE ]; then
-        	        rm -f $PIDSPATH/$PIDFILE
-	        fi
+        #Do default removal
+        if [ -f $PIDSPATH/$PIDFILE ]; then
+                    rm -f $PIDSPATH/$PIDFILE
+            fi
         fi
 }
- 
+
 start() {
         log_daemon_msg "Starting $DESCRIPTION"
- 
-	isRunning
-	isAlive=$?
- 
+
+    isRunning
+    isAlive=$?
+
         if [ "${isAlive}" -eq $TRUE ]; then
                 log_end_msg $SCRIPT_ERROR
         else
@@ -184,109 +184,109 @@ start() {
                 log_end_msg $SCRIPT_OK
         fi
 }
- 
+
 stop() {
-	log_daemon_msg "Stopping $DESCRIPTION"
- 
-	isRunning
-	isAlive=$?
+    log_daemon_msg "Stopping $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
         if [ "${isAlive}" -eq $TRUE ]; then
                 start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
- 
-		wait_for_pid 'removed' $PIDSPATH/$PIDFILE
- 
+
+        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+
                 if [ -n "$try" ] ; then
                         log_end_msg $SCRIPT_ERROR
                 else
                         removePIDFile
-	                log_end_msg $SCRIPT_OK
+                    log_end_msg $SCRIPT_OK
                 fi
- 
+
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 reload() {
-	configtest || return $?
- 
-	log_daemon_msg "Reloading (via HUP) $DESCRIPTION"
- 
+    configtest || return $?
+
+    log_daemon_msg "Reloading (via HUP) $DESCRIPTION"
+
         isRunning
         if [ $? -eq $TRUE ]; then
-		`killall -HUP $PS` #to be safe
- 
+        `killall -HUP $PS` #to be safe
+
                 log_end_msg $SCRIPT_OK
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 quietupgrade() {
-	log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
- 
+    log_daemon_msg "Peforming Quiet Upgrade $DESCRIPTION"
+
         isRunning
         isAlive=$?
         if [ "${isAlive}" -eq $TRUE ]; then
-		kill -USR2 `cat $PIDSPATH/$PIDFILE`
-		kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
- 
-		isRunning
-		isAlive=$?
-		if [ "${isAlive}" -eq $TRUE ]; then
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+        kill -USR2 `cat $PIDSPATH/$PIDFILE`
+        kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
+
+        isRunning
+        isAlive=$?
+        if [ "${isAlive}" -eq $TRUE ]; then
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
                         removePIDFile $PIDSPATH/$PIDFILE.oldbin
- 
-			log_end_msg $SCRIPT_OK
-		else
-			log_end_msg $SCRIPT_ERROR
- 
-			log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
- 
-			kill -HUP `cat $PIDSPATH/$PIDFILE`
-			kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
- 
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+
+            log_end_msg $SCRIPT_OK
+        else
+            log_end_msg $SCRIPT_ERROR
+
+            log_daemon_msg "ERROR! Reverting back to original $DESCRIPTION"
+
+            kill -HUP `cat $PIDSPATH/$PIDFILE`
+            kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
                         removePIDFile $PIDSPATH/$PIDFILE.oldbin
- 
-			log_end_msg $SCRIPT_ok
-		fi
+
+            log_end_msg $SCRIPT_ok
+        fi
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 terminate() {
         log_daemon_msg "Force terminating (via KILL) $DESCRIPTION"
- 
-	PIDS=`pidof $PS` || true
- 
-	[ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
- 
-	for i in $PIDS; do
-		if [ "$i" = "$PIDS2" ]; then
-	        	kill $i
+
+    PIDS=`pidof $PS` || true
+
+    [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
+
+    for i in $PIDS; do
+        if [ "$i" = "$PIDS2" ]; then
+                kill $i
                         wait_for_pid 'removed' $PIDSPATH/$PIDFILE
-			removePIDFile
-		fi
-	done
- 
-	log_end_msg $SCRIPT_OK
+            removePIDFile
+        fi
+    done
+
+    log_end_msg $SCRIPT_OK
 }
- 
+
 destroy() {
-	log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
-	killall $PS -q >> /dev/null 2>&1
-	log_end_msg $SCRIPT_OK
+    log_daemon_msg "Force terminating and may include self (via KILLALL) $DESCRIPTION"
+    killall $PS -q >> /dev/null 2>&1
+    log_end_msg $SCRIPT_OK
 }
- 
+
 pidof_daemon() {
     PIDS=`pidof $PS` || true
- 
+
     [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
- 
+
     for i in $PIDS; do
         if [ "$i" = "$PIDS2" ]; then
             return 1
@@ -294,43 +294,43 @@ pidof_daemon() {
     done
     return 0
 }
- 
+
 case "$1" in
   start)
-	start
+    start
         ;;
   stop)
-	stop
+    stop
         ;;
   restart|force-reload)
-	stop
-	sleep 3 
-	start
+    stop
+    sleep 3
+    start
         ;;
   reload)
-	$1
-	;;
+    $1
+    ;;
   status)
-	status
-	;;
+    status
+    ;;
   configtest)
         $1
         ;;
   quietupgrade)
-	$1
-	;;
+    $1
+    ;;
   terminate)
-	$1
-	;;
+    $1
+    ;;
   destroy)
-	$1
-	;;
+    $1
+    ;;
   *)
-	FULLPATH=/etc/init.d/$PS
-	echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
-	echo "       The 'destroy' command should only be used as a last resort." 
-	exit 1
-	;;
+    FULLPATH=/etc/init.d/$PS
+    echo "Usage: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
+    echo "       The 'destroy' command should only be used as a last resort."
+    exit 1
+    ;;
 esac
- 
+
 exit 0
